from flask_restful import reqparse

# Things needed to make a request below

# Parsing the request for receivers
wrArgs = reqparse.RequestParser()
wrArgs.add_argument("name",type=str,help="You need to add the Name",required=True)
wrArgs.add_argument("team",type=str,help="You need to add the Team",required=True)
wrArgs.add_argument("position",type=str,help="You need to add the Position",required=True)
wrArgs.add_argument("number",type=str,help="You need to add the Number",required=True)
wrArgs.add_argument("year",type=str,help="You need to add year",required=True)
wrArgs.add_argument("TGTS",type=str,help="You need to add year",required=True)
wrArgs.add_argument("GP",type=str,help="You need to add the games",required=True)
wrArgs.add_argument("REC",type=str,help="You need to add receptions",required=True)
wrArgs.add_argument("YDS",type=str,help="You need to add the yards",required=True)
wrArgs.add_argument("AVG",type=str,help="You need to add the avgYards",required=True)
wrArgs.add_argument("LNG",type=str,help="You need to add longestRec",required=True)
wrArgs.add_argument("TDS",type=str,help="You need to add tds",required=True)
wrArgs.add_argument("FD",type=str,help="You need to add receivingFirstDowns",required=True)
wrArgs.add_argument("FUM",type=str,help="You need to add fumbles",required=True)
wrArgs.add_argument("LST",type=str,help="You need to add rushingFumbleLost",required=True)

# Parsing the request for quarterbacks
qbArgs = reqparse.RequestParser()
qbArgs.add_argument("name",type=str,help="You need to add the Name",required=True)
qbArgs.add_argument("team",type=str,help="You need to add the Team",required=True)
qbArgs.add_argument("position",type=str,help="You need to add the Position",required=True)
qbArgs.add_argument("number",type=str,help="You need to add the Number",required=True)

qbArgs.add_argument("year",type=str,help="You need to add year",required=True)
qbArgs.add_argument("GP",type=str,help="You need to add the games",required=True)
qbArgs.add_argument("ATT",type=str,help="You need to add attempts",required=True)
qbArgs.add_argument("CMP",type=str,help="You need to add completions",required=True)
qbArgs.add_argument("CMP%",type=str,help="You need to add the completionPercent",required=True)
qbArgs.add_argument("YDS",type=str,help="You need to add yards",required=True)
qbArgs.add_argument("AVG",type=str,help="You need to add tds",required=True)
qbArgs.add_argument("LNG",type=str,help="You need to add longestPass",required=True)
qbArgs.add_argument("TDS",type=str,help="You need to add tds",required=True)
qbArgs.add_argument("INT",type=str,help="You need to add ints",required=True)
qbArgs.add_argument("SACK",type=str,help="You need to add sacks",required=True)
qbArgs.add_argument("FUM",type=str,help="You need to add fumbles",required=True)
qbArgs.add_argument("RTG",type=str,help="You need to add passerRating",required=True)
qbArgs.add_argument("QBR",type=str,help="You need to add qbr",required=True)

# Parsing the request for rushers
rbArgs = reqparse.RequestParser()
rbArgs.add_argument("name",type=str,help="You need to add the Name",required=True)
rbArgs.add_argument("team",type=str,help="You need to add the Team",required=True)
rbArgs.add_argument("position",type=str,help="You need to add the Position",required=True)
rbArgs.add_argument("number",type=str,help="You need to add the Number",required=True)
rbArgs.add_argument("year",type=str,help="You need to add year",required=True)
rbArgs.add_argument("GP",type=str,help="You need to add the games",required=True)
rbArgs.add_argument("ATT",type=str,help="You need to add attempts",required=True)
rbArgs.add_argument("YDS",type=str,help="You need to add the yards",required=True)
rbArgs.add_argument("AVG",type=str,help="You need to add the avgYards",required=True)
rbArgs.add_argument("LNG",type=str,help="You need to add longestRun",required=True)
rbArgs.add_argument("TDS",type=str,help="You need to add tds",required=True)
rbArgs.add_argument("FD",type=str,help="You need to add rushing1stDowns",required=True)
rbArgs.add_argument("FUM",type=str,help="You need to add fumbles",required=True)
rbArgs.add_argument("LST",type=str,help="You need to add rushingFumbleLost",required=True)

# Parsing the request for defensive positions
dfArgs = reqparse.RequestParser()
dfArgs.add_argument("name",type=str,help="You need to add the Name",required=True)
dfArgs.add_argument("team",type=str,help="You need to add the Team",required=True)
dfArgs.add_argument("position",type=str,help="You need to add the Position",required=True)
dfArgs.add_argument("number",type=str,help="You need to add the Number",required=True)

dfArgs.add_argument("year",type=str,help="You need to add year",required=True)
dfArgs.add_argument("GP",type=str,help="You need to add the games",required=True)
dfArgs.add_argument("TOT",type=str,help="You need to add the total Tackles",required=True)
dfArgs.add_argument("SOLO",type=str,help="You need to add the solo tackles",required=True)
dfArgs.add_argument("AST",type=str,help="You need to add the assisted tackles",required=True)
dfArgs.add_argument("SACK",type=str,help="You need to add the sacks",required=True)
dfArgs.add_argument("PD",type=str,help="You need to add the passes defended",required=True)
dfArgs.add_argument("FF",type=str,help="You need to add the forcedFumbles",required=True)
dfArgs.add_argument("FR",type=str,help="You need to add the fumblesRecovered",required=True)
dfArgs.add_argument("YDS",type=str,help="You need to add the fumbleYards",required=True)
dfArgs.add_argument("INT YARDS",type=str,help="You need to add the intYards",required=True)
dfArgs.add_argument("AVG",type=str,help="You need to add the avgYardsIntercepted",required=True)
dfArgs.add_argument("TDS",type=str,help="You need to add the tds",required=True)
dfArgs.add_argument("LNG",type=str,help="You need to add the longestInterception",required=True)
dfArgs.add_argument("STF",type=str,help="You need to add the stuffs",required=True)
dfArgs.add_argument("INT",type=str,help="You need to add the interceptions",required=True)
